defaults: &defaults
  # Storage configuration
  storage:
    
    # Cache root path
    cache.root: 'tmp/cache'
  
  # Console output configuration 
  output:

    # Colored output
    colors: true
    
    # Verbose output
    verbose: true

development:
  <<: *defaults  

test:
  <<: *defaults  
  
  output:
    colors: false
    verbose: false

production:
  <<: *defaults
  
  output:
    colors: false
    verbose: false
