defaults: &defaults
  # Storage configuration
  storage:

    # Cache root path
    cache:
      root: 'tmp/cache'

  # Console output configuration 
  output:

    # Colored output
    colors: false

    # Verbose output
    verbose: false

development:
  <<: *defaults

  output:
    colors: true
    verbose: true

test:
  <<: *defaults  

staging:
  <<: *defaults

production:
  <<: *defaults
