# TODO refactor settingslogic shit, because it does not merge hashes, it directly sets values

defaults: &defaults
  # Storage configuration
  storage:

    # Cache root path
    cache:
      root: 'tmp/cache'

  # Console output configuration 
  output:

    # Colored output
    colors: true

    # Verbose output
    verbose: true

development:
  <<: *defaults  

test:
  <<: *defaults  

  # TODO settingslogic shit
  output:
    colors: false
    verbose: false

staging:
  <<: *defaults

  # TODO settingslogic shit
  output:
    colors: true
    verbose: true

production:
  <<: *defaults

  # TODO settingslogic shit
  output:
    colors: true
    verbose: true # TODO set to false when production is set up
