defaults: &defaults
  # Storage configuration
  storage:
    
    # Storage root path
    root: 'storage'
  
  # Resources configuration
  resource:
    
    # List of resources updateable by crawlers
    updateable: [Court, Judge, Hearing, Decree]
  
  # Extractor configuration
  extractor:
    
    # Perform image extraction on specified resources if possible  
    image.perform: [Decree]
      
    # Override existing image extractions for specified resources
    image.override: [Decree]

    # Perform text extraction on specified resources if possible
    text.perform: [Decree]

    # Override existing text extractions for specified resources
    text.override: [Decree]

development:
  <<: *defaults 
  
  extractor.image.perform: []

test:
  <<: *defaults
  
  resource.updateable: [Court, Judge]

production:
  <<: *defaults
  
  resource.updateable: [Court, Judge]
