# TODO refactor settingslogic shit, because it does not merge hashes, it directly sets values

defaults: &defaults
  # Storage configuration
  storage:

    # Storage root path
    root: 'storage'

  # Resources configuration
  resource:

    # List of resources updateable by crawlers
    updateable: [Court, Judge, Hearing, Decree]

  # Extractor configuration
  extractor:

    image:
      # Perform image extraction on specified resources if possible
      perform: [Decree]

      # Override existing image extractions for specified resources
      override: []

    text:
      # Perform text extraction on specified resources if possible
      perform: [Decree]

      # Override existing text extractions for specified resources
      override: [Decree]

development:
  <<: *defaults 

  # TODO settingslogic shit
  extractor:

    image:
      perform: []
      override: []

    text:
      perform: [Decree]
      override: [Decree]

test:
  <<: *defaults

  # TODO settingslogic shit
  resource:
    updateable: [Court, Judge]

staging:
  <<: *defaults

  # TODO settingslogic shit
  resource:
    updateable: [Court, Judge]

production:
  <<: *defaults

  # TODO rm
  extractor:

    image:
      perform: [Decree]
      override: []

    text:
      perform: [Decree]
      override: [Decree]

  # TODO settingslogic shit
  resource:
    updateable: [Court, Judge]
