defaults: &defaults
  # Storage configuration
  storage:
    
    # Storage root path
    root: 'storage'
  
  # Resources configuration
  resource:
    
    # List of resources updateable by crawlers
    updateable: [Court, Judge, Hearing, Decree]
  
  # Extractor configuration
  extractor:
    
    image:
      # Perform image extraction on specified resources if possible
      perform: [Decree]
      
      # Override existing image extractions for specified resources
      override: [Decree]

    text:
      # Perform text extraction on specified resources if possible
      perform: [Decree]

      # Override existing text extractions for specified resources
      override: [Decree]

development:
  <<: *defaults 
  
  # TODO refactor settingslogic shit, because it does not merge hashes, it directly sets values
  extractor:
    image:
      perform: []
      override: []
    text:
      perform: [Decree]
      override: [Decree]

test:
  <<: *defaults
  
  # TODO refactor settingslogic shit, because it does not merge hashes, it directly sets values
  resource:
    updateable: [Court, Judge]
      
production:
  <<: *defaults
  
  # TODO refactor settingslogic shit, because it does not merge hashes, it directly sets values
  resource:
    updateable: [Court, Judge]
