defaults: &defaults
  indices: [courts, judges, hearings, decrees, decree_pages, proceedings]

  per_page: 20

  index:
    number_of_shards: 1
    number_of_replicas: 1

    analysis:
      analyzer:
        text_analyzer:
          type: custom
          tokenizer: standard
          filter: [asciifolding, lowercase, trim]

        normalizer:
          type: custom
          tokenizer: keyword
          filter: [asciifolding, lowercase, trim]

  suggest:
    separator: ':'

    matcher:
      name: suggest_matcher

      params:
        separator: ':'

      script: "
          values = term.split(params['separator']);

          foreach(q : params['query'])
          {
            if (!values[1].contains(q))
            {
              return null;
            }
          }

          return values[0];
        "
development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
