defaults: &defaults
  indices: [Decree, Hearing, Court, Judge, DecreePage]

  default_analyzer: text_analyzer
  per_page: 20

  index:
    number_of_shards: 1
    number_of_replicas: 1

    analysis:
      analyzer:
        text_analyzer:
          type: custom
          tokenizer: standard
          filter: [asciifolding, lowercase, trim]

  script:
    suggest:
      name: suggest_matcher
      script: '
        import org.apache.lucene.analysis.miscellaneous.ASCIIFoldingFilter;

        analyze = def (s) {
          size   = s.length();
          result = new char[size];

          ASCIIFoldingFilter.foldToASCII(s.toCharArray(), 0, result, 0, size);

          return new String(result).toLowerCase();
        };

        value = analyze(term);
        query = analyze(query);

        if (!value.contains(query)) {
            return null;
        }

        return term;
        '

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
